output "instance_public_ip" {
  description = "The public IP address of the EC2 instance"


















































































































































































```→ Deploy to EC2 → App Live at 3.83.237.70→ Terraform Init & Plan → Terraform Apply→ Build Docker Images → Push to Docker HubGitHub Push → GitHub Webhook → Jenkins Trigger```**Auto-Deploy Workflow:**---5. ✅ Access your app at http://3.83.237.704. ✅ Monitor Jenkins build progress3. ✅ Push a test commit to main branch2. ✅ Test local builds with `./scripts/build-wsl.sh`1. ✅ Add Jenkins credentials (see Prerequisites Setup)## Next Steps```terraform destroy  # Removes all AWS resources```bash- To avoid charges: Terraform destroy after testing- Using low-cost networking- Using t3.micro instance (eligible for AWS free tier)## Cost Optimization```    - DATABASE_URL=your-database-url    - SUPABASE_SERVICE_KEY=your-service-key    - SUPABASE_URL=your-supabase-url    - PORT=4000  environment:backend:```yamlThe docker-compose file already contains your Supabase credentials. To update:## Environment Variables in docker-compose.yml- Verify security group allows HTTP (port 80) from 0.0.0.0/0- View logs: `docker-compose logs -f`- Check: `docker-compose ps` on EC2- Wait 30-60 seconds for containers to fully start### Application Not Accessible at http://3.83.237.70- Monitor: `docker-compose logs backend` & `docker-compose logs frontend`- Check internet connectivity on EC2- Verify Docker Hub credentials are correct### Docker Pull Fails on EC2- Verify ruhuna-key.pub is correctly imported to AWS- Check security group allows SSH (port 22) from Jenkins server- EC2 instance takes 2-3 minutes to fully initialize### SSH Connection Timeout- Check IAM user has EC2, VPC, and Security Group permissions- Verify AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY credentials exist- Check AWS credentials in Jenkins### Pipeline Fails at Terraform Stage## Troubleshooting```docker-compose logs -fdocker-compose psssh -i ruhuna-key ubuntu@3.83.237.70```bash### SSH to EC2 Instance```terraform output instance_ipterraform applyterraform planterraform initcd terraform```bash### Manual Terraform Commands3. Click "Build Now"2. Select your pipeline job1. Open Jenkins UI### Run Pipeline Manually## Manual Triggers (If Needed)```  └── build-windows.ps1 → Windows build helper  ├── build-wsl.sh   → WSL build helperscripts/terraform/           → (Optional) If you organize Terraform separatelydocker-compose.yml   → Container orchestration for AWSjenkinsfile.groovy   → CI/CD pipeline stagesoutputs.tf           → Terraform outputs (instance IP)main.tf              → AWS infrastructure definition```## File Structure Reference- Starts containers with docker-compose up -d- Pulls latest Docker images- Copies docker-compose.yml to EC2- Waits for SSH access to be ready (up to 5 minutes)### Stage 6: Deploy to AWS EC2- Saves instance IP for next stage- Installs Docker & Docker Compose on EC2- Creates security groups- Provisions EC2 instance (t3.micro - free tier eligible)### Stage 5: Terraform Apply- Shows what resources will be created/modified- Creates execution plan (tfplan)- Initializes Terraform state### Stage 4: Terraform Init & PlanAuthenticates with Docker Hub and pushes both images### Stage 3: Push to Docker Hub```docker build -t wmdeneth/backend-app:latest -f backend/Dockerfile backenddocker build -t wmdeneth/frontend-app:latest -f frontend/Dockerfile frontend```bash### Stage 2: Build Docker ImagesFetches your latest code from GitHub main branch### Stage 1: Clone Repository## Pipeline Stages Explained- Active: ✓- Events: Push events- Content type: `application/json`- Payload URL: `http://your-jenkins-server:8080/github-webhook/`In your GitHub repository (Settings → Webhooks):### 3. GitHub Webhook Setup```sudo apt update && sudo apt install terraformecho "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.listwget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg```bashInside WSL, install Terraform:```wsl -d Ubuntu-22.04```powershellRun from PowerShell (Windows):### 2. Local WSL Setup  - Paste your ruhuna-key private key content- **AWS_SSH_KEY** (SSH key)  - Your AWS secret key- **AWS_SECRET_ACCESS_KEY** (Secret text)  - Your AWS access key- **AWS_ACCESS_KEY_ID** (Secret text)  - Password: your Docker Hub token/password  - Username: your Docker Hub username- **dockerhub** (Username with password)Add these credentials in Jenkins UI (Manage Jenkins → Manage Credentials):### 1. Jenkins Credentials## Prerequisites Setup5. Makes app available at http://3.83.237.704. Deploys containers to AWS3. Provisions AWS EC2 infrastructure with Terraform2. Pushes to Docker Hub1. Builds Docker images (frontend + backend)Your pipeline now automatically:## Overview  value       = aws_instance.project_server.public_ip
}

output "instance_ip" {
  description = "Raw EC2 instance public IP for deployment scripts"
  value       = aws_instance.project_server.public_ip
}
